workflows:
  android-gradle-release:
    name: Android Gradle Release Build
    max_build_duration: 60
    environment:
      java: 17
    cache:
      cache_paths:
        - ~/.gradle
        - ~/.android
        - build/
    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build Release APK
        script: ./gradlew assembleRelease --stacktrace --info

      - name: Verify outputs
        script: |
          echo "✅ Build completed. Listing outputs:"
          find . -type f \( -name "*.apk" -o -name "*.aab" \)

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
