workflows:
  android-gradle-release:
    name: Android Gradle Release Build
    max_build_duration: 60
    environment:
      java: 17
      android: latest
      vars:
        GRADLEW_PATH: "./gradlew"
        BUILD_TYPE: "Release"
      cache:
        cache_paths:
          - ~/.gradle
          - ~/.android
          - build/
    scripts:
      - name: Make gradlew executable
        script: chmod +x $GRADLEW_PATH

      - name: Clean project
        script: $GRADLEW_PATH clean

      - name: Build Release APK
        script: $GRADLEW_PATH assembleRelease

      - name: (Optional) Build App Bundle (AAB)
        script: $GRADLEW_PATH bundleRelease

      - name: Verify outputs
        script: |
          echo "APK files:"
          find . -name "*.apk"
          echo "AAB files:"
          find . -name "*.aab"

      - name: (Optional) Sign APK manually
        script: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
          -keystore $CM_KEYSTORE_PATH -storepass $KEYSTORE_PASSWORD \
          -keypass $KEY_PASSWORD app/build/outputs/apk/release/app-release-unsigned.apk $KEY_ALIAS

          zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk \
          app/build/outputs/apk/release/app-release-signed.apk

    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
